version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 12.x
  build:
    commands:
      - sam package --template-file template.yml --s3-bucket sam-app --output-template-file packaged-template.yml
artifacts:
  files:
    - packaged-template.yml